### ISSUE TITLE
AttributeError: 'module' object has no attribute 'REQUIRE_VERSION'

### ISSUE THREAD

**Issue by tancque** [proycon/clam#58]
An error came up with starting a clamservice (piccl) after updateing LaMachine to latest version.

```
Traceback (most recent call last):
  File "/vol1/LaMachine/lamachine/bin/clamservice", line 11, in <module>
    load_entry_point('CLAM==2.2.1', 'console_scripts', 'clamservice')()
  File "/vol1/LaMachine/lamachine/lib/python3.4/site-packages/clam/clamservice.py", line 2801, in main
    test_version()
  File "/vol1/LaMachine/lamachine/lib/python3.4/site-packages/clam/clamservice.py", line 2727, in test_version
    req = str(settings.REQUIRE_VERSION).split('.')
AttributeError: 'module' object has no attribute 'REQUIRE_VERSION'
```
This happend with the installed servicefile and our own editited picclservice.py.
Commenting the REQUIRE_VERSION property in the servicefile had no effect.
Added Version file of lamachine

**Comment by proycon** [comment]
Hmm.. interesting. This isn't really something I touched in the last update. The REQUIRE_VERSION line in picclservice.py should be *uncommented* and set to something like ``REQUIRE_VERSION = 2.1``

**Comment by tancque** [comment]
Tried again by changing REQUIRE_VERSION to 2.2 and 2.2.1  from 0.99. Same error. The setting seems not to be parsed.

**Comment by proycon** [comment]
I'm quite puzzled about this... If ``REQUIRE_VERSION`` is set and the settings imports without error, then this error should be impossible.  It's as if it imports the wrong thing entirely then or is working on an older cached version. You're in the LaMachine virtualenv flavour and restarting clamservice yourself right? Or are you already in a more production-oriented WSGI setup? Can you show your entire service configuration again just to be sure?

**Comment by tancque** [comment]
Did some more debugging: 
- Created fresh centos 7 vm.
- checked out lamachine, bootstrapped virtualenv and run the update script (to be sure)
- activated lamachine and started "clamservice picclservice" -> Require_version error

Did the same with lsof running  to check open files during script-startup. lsof seem to indicate that the Piccl package dir was touched, but not the servicefile "picclservice.py" (lsof file included)
To verify i did a strace (file included) and again found no Open calls for the picclservice.py file, only for the package files.  I might be interpreting the trace wrong, but it seems to indicate that the config file is not parsed. 

To check if there seem to be something wrong with the paths in the virtualenv I started clam with a made-up, not existing service-config file "marco". This produced error "no module named "marco". This indicates that the piccle-servicefiles are in the right spot/path

Dubbelchecked file permissions : 0755 and selinux disabled. Tried with 777, with no effect.

Included are the openfiles and trace of the proces start.
[openfiles_clam.txt](https://github.com/proycon/clam/files/1471518/openfiles_clam.txt)
[strace.txt](https://github.com/proycon/clam/files/1471537/strace.txt)

As requested : service configuration used 
[picclservice.py.txt](https://github.com/proycon/clam/files/1471614/picclservice.py.txt)

**Comment by proycon** [comment]
Sorry for not getting back to you yet, I'll try to do so next week!

**Comment by proycon** [comment]
Thanks for all the debugging! In the end it all turns out to make sense and prove to be an easy oversight after all. Here we go:

I see you run ``clamservice picclservice`` but it should be ``clamservice picclservice.picclservice``. The PICCL documentation does state it correctly but I had overlooked it in your report here as well.   The entire module is installed as ``picclservice`` package with a ``picclservice`` the module inside it. The devil is in the details.. If you invoke it with ``picclservice.picclservice`` correctly it should parse the intended file, in your case ``/vol1/lamachine/lib/python3.4/site-packages/PICCL-0.4-py3.4.egg/picclservice/picclservice.py``, otherwise it just loaded the packages ``__init__.py`` probably which is empty and indeed does not have a ``REQUIRE_VERSION``, hence our previously mysterious but finally exposed  error message..

**Comment by tancque** [comment]
<facepalm>
Tested and it works. Sorry for the oversight.
